version: '3.5'

services:
  api:
    command: bash -c "cp env/.env.development app.env"
    container_name: api
    build: 
      context: ../build
      dockerfile: dev.Dockerfile
    depends_on:
      - db
    networks:
      - db_postgresql
    restart: always
    env_file:
      - ../.env
    volumes:
      - ../:/app
    ports:
      - "${PORT_SERVER}:${PORT_SERVER}"
  db:
    container_name: db_postgresql
    image: postgres:16.3
    ports:
      - 5434:5432
    restart: always
    env_file:
      - ../.env
    networks:
      - db_postgresql
    volumes:
      - db_postgresql:/var/lib/postgresql/data
      - ../initdb:/docker-entrypoint-initdb.d


volumes:
  db_postgresql:
networks:
  db_postgresql:
    driver: bridge