basePath: /api/v1
definitions:
  model.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.LoginResponse:
    properties:
      expired_at:
        type: string
      refresh_token:
        type: string
      token:
        type: string
    type: object
  model.PaginationModel:
    properties:
      current_page:
        type: integer
      per_page:
        type: integer
      total_data:
        type: integer
      total_page:
        type: integer
    type: object
  model.PaginationRequest:
    properties:
      filter:
        additionalProperties: true
        type: object
      page:
        type: integer
      per_page:
        type: integer
    type: object
  model.PaginationResponse:
    properties:
      data: {}
      metadata:
        $ref: '#/definitions/model.PaginationModel'
    type: object
  model.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
  model.Response:
    properties:
      response_data: {}
      response_error:
        type: string
      response_message:
        type: string
    type: object
  model.UserCreateRequest:
    properties:
      email:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
  model.UserResponse:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      deleted_at:
        type: string
      deleted_by:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      phone_number:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
      user_code:
        type: integer
      uuid:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
  description: Money Tracking Service.
  termsOfService: http://swagger.io/terms/
  title: My API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login Request
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  $ref: '#/definitions/model.LoginResponse'
              type: object
      summary: Login
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: Register Request
        in: body
        name: registerRequest
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  type: string
              type: object
      summary: Register
      tags:
      - auth
  /users/create:
    post:
      description: Create a new user
      parameters:
      - description: Body User Create
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.UserCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success create user
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Create a new user
      tags:
      - Users
  /users/list:
    post:
      description: Retrieves a list of users
      parameters:
      - description: Body Pagination
        in: body
        name: body
        schema:
          $ref: '#/definitions/model.PaginationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success get list user
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  allOf:
                  - $ref: '#/definitions/model.PaginationResponse'
                  - properties:
                      data:
                        $ref: '#/definitions/model.UserResponse'
                    type: object
              type: object
      security:
      - ApiKeyAuth: []
      summary: Get a list of users
      tags:
      - Users
produces:
- application/json
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
