basePath: /api/v1
definitions:
  http.CreateUserRequest:
    type: object
  http.ErrorResponse:
    type: object
  http.UpdateUserRequest:
    type: object
  http.UserResponse:
    type: object
  model.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.LoginResponse:
    properties:
      expired_at:
        type: string
      refresh_token:
        type: string
      token:
        type: string
    type: object
  model.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
  model.Response:
    properties:
      response_data: {}
      response_error:
        type: string
      response_message:
        type: string
    type: object
  model.RoleCreateRequest:
    properties:
      alias:
        type: string
      name:
        type: string
    type: object
  model.UserCreateRequest:
    properties:
      email:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
  model.UserResponse:
    properties:
      created_at:
        type: string
      created_by:
        type: integer
      deleted_at:
        type: string
      deleted_by:
        type: integer
      email:
        type: string
      id:
        type: integer
      phone_number:
        type: string
      updated_at:
        type: string
      updated_by:
        type: integer
      user_code:
        type: integer
      uuid:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
  description: Money Tracking Service.
  termsOfService: http://swagger.io/terms/
  title: My API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login Request
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  $ref: '#/definitions/model.LoginResponse'
              type: object
      summary: Login
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: Register Request
        in: body
        name: registerRequest
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  type: string
              type: object
      summary: Register
      tags:
      - auth
  /roles/:
    post:
      consumes:
      - application/json
      description: Create Role
      parameters:
      - description: Role Create Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.RoleCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully create role
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Create Role
      tags:
      - Role
  /users/:
    post:
      consumes:
      - application/json
      description: Creates a new user
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/http.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/http.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Create a new user
  /users/{id}:
    delete:
      description: Deletes a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Delete a user by ID
    get:
      description: Retrieves a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Create a new user
      tags:
      - Users
  /users/{user_code}:
    get:
      description: Get User
      parameters:
      - description: user_code user
        in: path
        name: user_code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success Get user
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  $ref: '#/definitions/model.UserResponse'
              type: object
      security:
      - ApiKeyAuth: []
      summary: Get User
      tags:
      - Users
  /users/{uuid}:
    delete:
      description: Delete a new user
      parameters:
      - description: uuid user
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success delete user
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Delete user
      tags:
      - Users
    put:
      description: Update User
      parameters:
      - description: uuid user
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success update user
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                response_data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Update User
      tags:
      - Users
  /users/list:
    post:
      description: Retrieves a list of users
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/http.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Update an existing user
swagger: "2.0"
