# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    environment: staging
    runs-on: self-hosted
    name: respati-vps
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'
    
    - name: Set Environtment variables
      run: echo {{ secrets.DBURL }} >> .env

    - name: Build
      run: docker build -t myapp-prod -f ./build/Dockerfile .
  
  deploy:
    environment: staging
    runs-on: self-hosted
    name: respati-vps
    steps:
      - name: Docker run myapp-prod
        run: | 
          docker stop myapp-prod || true
          docker rm myapp-prod || true
          docker run -d --name myapp-prod -p 8080:8080 myapp-prod:latest